version: "3.9"

services:
    pwreverseproxy:
        image: "ghcr.io/myrkgard/pwreverseproxy:latest"
        ports:
            - "80:80"
        depends_on:
            - pwwebsite
            - pwapi

    pwwebsite:
        image: ghcr.io/myrkgard/pwwebsite:latest
        depends_on:
            - pwapi

    pwapi:
        image: ghcr.io/myrkgard/pwapi:latest
        environment:
            - MONGODB_CONNSTRING=mongodb://rootusername:rootpassword@pwmongodb

    pwmongodb:
        image: mongo
        volumes:
            - data:/data
        environment:
            - MONGO_INITDB_ROOT_USERNAME=rootusername
            - MONGO_INITDB_ROOT_PASSWORD=rootpassword

volumes:
    data: {}
